// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace OurCarZ.Model
{
    [Table("Address")]
    public partial class Address
    {
        public Address()
        {
            RouteFinishPointNavigations = new HashSet<Route>();
            RouteStartPointNavigations = new HashSet<Route>();
        }

        [Key]
        [Column("AddressID")]
        public int AddressId { get; set; }
        [Required]
        [StringLength(50)]
        public string RoadName { get; set; }
        public int ZipCode { get; set; }
        [StringLength(30)]
        public string Country { get; set; }

        [InverseProperty(nameof(Route.FinishPointNavigation))]
        public virtual ICollection<Route> RouteFinishPointNavigations { get; set; }
        [InverseProperty(nameof(Route.StartPointNavigation))]
        public virtual ICollection<Route> RouteStartPointNavigations { get; set; }
    }
}