// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace OurCarZ.Model
{
    [Table("RatingDB")]
    public partial class RatingDb
    {
        public RatingDb()
        {
            Users = new HashSet<User>();
        }

        [Key]
        [Column("RatingID")]
        public int RatingId { get; set; }
        public int? Rating { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("RatingDbs")]
        public virtual User User { get; set; }
        [InverseProperty("Rating")]
        public virtual ICollection<User> Users { get; set; }
    }
}