// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace OurCarZ.Model
{
    [Keyless]
    [Table("RatingDatabase")]
    public partial class RatingDatabase
    {
        [Column("UserRatedID")]
        public int? UserRatedId { get; set; }
        public int? Rating { get; set; }
        [Column("UserRatingID")]
        public int? UserRatingId { get; set; }

        [ForeignKey(nameof(UserRatedId))]
        public virtual User UserRated { get; set; }
        [ForeignKey(nameof(UserRatingId))]
        public virtual User UserRating { get; set; }
        public RatingDatabase()
        {

        }
        public RatingDatabase(int Rater, int rating, int Rated)
        {
            UserRatedId = Rated;
            Rating = rating;
            UserRatingId = Rater;
        }
    }
}