// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace OurCarZ.Model
{
    [Table("Route")]
    public partial class Route
    {
        public Route()
        {
            UserRoutes = new HashSet<UserRoute>();
        }

        public Route(int id, string sp, string fp)
        {
            RouteId = id;
            StartPoint = sp;
            FinishPoint = fp;
        }

        [Key]
        [Column("RouteID")]
        public int RouteId { get; set; }
        public int StartPoint { get; set; }
        public int FinishPoint { get; set; }
        [Column(TypeName = "date")]
        public DateTime StartTime { get; set; }
        public string StartPoint { get; set; }
        public string FinishPoint { get; set; }
        [Column("UserID")]
        public int? UserId { get; set; }

        [ForeignKey(nameof(FinishPoint))]
        [InverseProperty(nameof(Address.RouteFinishPointNavigations))]
        public virtual Address FinishPointNavigation { get; set; }
        [ForeignKey(nameof(StartPoint))]
        [InverseProperty(nameof(Address.RouteStartPointNavigations))]
        public virtual Address StartPointNavigation { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Routes")]
        public virtual User User { get; set; }
        [InverseProperty(nameof(UserRoute.Route))]
        public virtual ICollection<UserRoute> UserRoutes { get; set; }
    }
}