// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

#nullable disable

namespace OurCarZ.Model
{
    [Table("UserRoute")]
    public partial class UserRoute
    {
        [Key]
        [Column("UserRouteID")]
        public int UserRouteId { get; set; }
        [Column("RouteID")]
        public int? RouteId { get; set; }
        [Column("UserID")]
        public int? UserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? PickupTime { get; set; }

        [ForeignKey(nameof(RouteId))]
        [InverseProperty("UserRoutes")]
        public virtual Route Route { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserRoutes")]
        public virtual User User { get; set; }
    }
}